# Generated by Django 5.0 on 2023-12-06 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.IntegerField()),
                ('uname', models.CharField(max_length=32)),
                ('uloc', models.CharField(max_length=32)),
            ],
        ),
    ]
